### ISSUE TITLE
Do not rely on experimental global fetch node API

### ISSUE THREAD

**Issue by fiws** [googleapis/nodejs-vertexai#133] opened 2024-01-14 11:21 UTC
The `fetch` api [used in this library](https://github.com/googleapis/nodejs-vertexai/blob/main/src/util/post_request.ts#L55) is considered [experimental](https://nodejs.org/dist/latest-v18.x/docs/api/globals.html#fetch).

I can think of a few reasons why this might be a bad idea:
* Node could break this api any minute, thus breaking this library and your customers code
* Other node-like environments (like deno or bun) might not implement fetch in the same way node does, thus making this library incompatible with them
* Libraries like remix patch the way fetch works, breaking this library

**Is your feature request related to a problem? Please describe.**

I ran into this problem using remix. They apparently are patching fetch, more specifically `ReadableStream` with [web-stream-polyfill](https://github.com/MattiasBuelens/web-streams-polyfill) which breaks vertexai:

```
TypeError: First parameter has member 'readable' that is not a ReadableStream.
    at assertReadableStream (/home/fiws/hydra/ai-demo/node_modules/web-streams-polyfill/src/lib/validators/readable-stream.ts:5:11)
    at convertReadableWritablePair (/home/fiws/hydra/ai-demo/node_modules/web-streams-polyfill/src/lib/validators/readable-writable-pair.ts:15:3)
    at ReadableStream.pipeThrough (/home/fiws/hydra/ai-demo/node_modules/web-streams-polyfill/src/lib/readable-stream.ts:223:23)
    at processStream (/home/fiws/hydra/nodejs-vertexai/src/process_stream.ts:60:38)
    at GenerativeModel.generateContentStream (/home/fiws/hydra/nodejs-vertexai/src/index.ts:460:39)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at GenerativeModel.generateContent (/home/fiws/hydra/nodejs-vertexai/src/index.ts:391:9)
```

**Describe the solution you'd like**
Don't rely on the experimental global fetch API. Instead either use a library like `cross-fetch` or rewrite the fetch code to use the stable https core library.

**Comment by rbasto1** [comment] 2024-01-19 18:08
I think the problem is with `web-streams-polyfill` when in Node (as opposed to the browser). We had the same issue and fixed it with a change to our Webpack configuration:
```
{
    resolve: {
      alias: {
        'web-streams-polyfill$': 'web-streams-polyfill/ponyfill/es2018',
      },
}
```

**Comment by yyyu-google** [comment] 2024-02-23 06:11
Thank you @rbasto1 for sharing your expertise. I am closing this comment now. Feel free to reopen if further issue occurs.

**Closed by yyyu-google** 2024-02-23 06:11 UTC
Labels: type: feature request, priority: p3, api: aiplatform

**Comment by nk-gears** [comment] 2024-02-28 11:50
When i integrated in a typescript project, i am getting fetch not defined. Is there any workaround ?

**Comment by fiws** [comment] 2024-02-28 11:55
@yyyu-google the workaround provided only works for webpack. Remix does not use webpack. It does not solve our issue. We resorted to using the REST api directly.

You may also want to read what I have written in my initial issue description. There are several valid reasons why this package should avoid using **experimental** Node.js APIs in the first place.

PS: I have no option to reopen.
